apiVersion: v1
kind: Namespace
metadata:
   name: game
   labels:
     name: game
---     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-deployment
  namespace: game
spec:
  selector:
    matchLabels:
      app: gate
  replicas: 1
  template:
    metadata:
      labels:
        app: gate
    spec:
      containers:
      - name: gate 
        image: xiancaige/gate:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 10010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: game
spec:
  selector:
    matchLabels:
      app: core
  replicas: 3
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: xiancaige/core
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: game
spec:
  selector:
    app: core
  ports:
  - name: tcp-9999
    protocol: TCP
    port: 9999
  - name: udp-6789
    protocol: UDP
    port: 6789
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: game
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: xiancaige/db

