apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-harbor-registry
  namespace: ci
spec:
  storageClassName: harbor-registry
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kubernetes/harbor/registry"
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ams 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-harbor-chartmuseum
  namespace: ci
spec:
  storageClassName: harbor-chartmuseum
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kubernetes/harbor/chartmuseum"
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ams 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-harbor-jobservice
  namespace: ci
spec:
  storageClassName: harbor-jobservice
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kubernetes/harbor/jobservice"
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tx
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-harbor-database
  namespace: ci
spec:
  storageClassName: harbor-database
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kubernetes/harbor/database"
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tx
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-harbor-redis
  namespace: ci
spec:
  storageClassName: harbor-redis
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kubernetes/harbor/redis"
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tx
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host-harbor-trivy
  namespace: ci
spec:
  storageClassName: harbor-trivy
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kubernetes/harbor/trivy"
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ams 
