apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-admin-role
  namespace: ci
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"] 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-admin-rolebinding
  namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-admin-role
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: ci
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ci
  name: jenkins-pod
  labels: 
    app: jenkins
spec:
  terminationGracePeriodSeconds: 10
  serviceAccountName: jenkins-admin
  containers:
  - name: jenkins
    image: jenkins/jenkins:2.332.1-lts-alpine
    stdin: true
    tty: true
    securityContext:                     
      runAsUser: 0                      #设置以ROOT用户运行容器
      privileged: true 
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: pvc1
      mountPath: /var/jenkins_home
    - name: k8s-config
      mountPath: /root/.kube/config
    ports:
    - containerPort: 8080
      name: web
      protocol: TCP
    - containerPort: 50000
      name: agent
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /login
        port: 8080
      initialDelaySeconds: 60
      timeoutSeconds: 5
      failureThreshold: 12
    readinessProbe:
      httpGet:
        path: /login
        port: 8080
      initialDelaySeconds: 60
      timeoutSeconds: 5
      failureThreshold: 12
  securityContext:
    fsGroup: 1000
  volumes:
    - name: pvc1
      persistentVolumeClaim:
        claimName: pvc-host
    - name: k8s-config
      hostPath:
        path: /root/.kube/config
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: ci
spec:
  selector:
    app: jenkins
  ports:
  - name: tcp
    protocol: TCP
    port: 8080
    nodePort: 30080
  - name: son
    protocol: TCP
    port: 50000
    targetPort: 50000
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-host
  namespace: ci
spec:
  storageClassName: jenkins-workspace
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kubernetes/jenkins_home"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tx3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-host
  namespace: ci
spec:
  storageClassName: jenkins-workspace
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
